# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xproblem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='user',
        ),
    ]
