# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('contest', '0008_contest_allowed_ip_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ManyToManyField(related_name='contests', to='user.Group'),
        ),
    ]
