# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='class_num',
            field=models.IntegerField(default=1, verbose_name='班级'),
            preserve_default=False,
        ),
    ]
