# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180406_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
