# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20180404_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_open_test_case',
            field=models.BooleanField(default=False, verbose_name='测试用例公开的题目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='有效题目'),
            preserve_default=False,
        ),
    ]
