# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_auto_20180406_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='vote_downs',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='vote_ups',
        ),
        migrations.AddField(
            model_name='problem',
            name='vote_rank_score',
            field=models.FloatField(default=0.0),
        ),
    ]
